name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release number e.g. 1.2.3'
        required: true
  #push:
  #  branches: [master]
  #  paths-ignore:
  #    - '**.md'
  #pull_request:
  #  branches: [master]
  #  paths-ignore:
  #    - '**.md'
env:
  ver_num: '${{ github.event.inputs.version }}'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Run Make
        run: 'VERSION=${{ env.ver_num }} make'

      - name: Package deb file
        run: 'VERSION=${{ env.ver_num }} make package'

      - name: Upload a Build Artifact - deb
        uses: actions/upload-artifact@v4.3.1
        with:
          name: 'i3-companion_${{ env.ver_num }}.deb'
          path: 'package/i3-companion_${{ env.ver_num }}.deb'
          if-no-files-found: error
          retention-days: 90

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifactErrorsFailBuild: true
          artifacts: 'package/i3-companion_${{ env.ver_num }}.deb'
          commit: '${{ github.sha }}'
          #draft: false
          tag: 'v${{ env.ver_num }}'
          name: 'v${{ env.ver_num }}'
          token: ${{ github.token }}
